//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildInstitutionTbl
    {
        public long Id { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public string NameOfTheOrganization { get; set; }
        public string TypeOfOrganization { get; set; }
        public string NameOfEmployee { get; set; }
        public string DesignationOfTheEmployee { get; set; }
        public Nullable<long> TehsilID { get; set; }
        public string ChildName { get; set; }
        public Nullable<double> ChildAge { get; set; }
        public string ChildGender { get; set; }
        public Nullable<long> ChildStateId { get; set; }
        public Nullable<long> ChildDistrictId { get; set; }
        public Nullable<long> ChildTehsil { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SocialCategory { get; set; }
        public Nullable<long> CategoryOfChild { get; set; }
        public string Otherillness { get; set; }
        public string ChildImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual ChildCategoryTbl ChildCategoryTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl1 { get; set; }
        public virtual StateMasterTbl StateMasterTbl { get; set; }
        public virtual StateMasterTbl StateMasterTbl1 { get; set; }
        public virtual TehsilMasterTbl TehsilMasterTbl { get; set; }
        public virtual TehsilMasterTbl TehsilMasterTbl1 { get; set; }
    }
}
