//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildParentConnectionTbl
    {
        public long Id { get; set; }
        public Nullable<long> ChildID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual ChildMasterTbl ChildMasterTbl { get; set; }
        public virtual ParentMasterTbl ParentMasterTbl { get; set; }
    }
}
