//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildMasterTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildMasterTbl()
        {
            this.ChildParentConnectionTbls = new HashSet<ChildParentConnectionTbl>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public long SerialNumber { get; set; }
        public Nullable<long> CCIMasterID { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public string ChildCode { get; set; }
        public string ChildName { get; set; }
        public string Sex { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<double> Age { get; set; }
        public string Education { get; set; }
        public string SocialGroup { get; set; }
        public string SpecialChild { get; set; }
        public string MothersName { get; set; }
        public string MothersCurrentStatus { get; set; }
        public string FathersName { get; set; }
        public string FathersCurrentStatus { get; set; }
        public Nullable<long> SistersCount { get; set; }
        public Nullable<long> BrothersCount { get; set; }
        public Nullable<long> SiblingCount { get; set; }
        public string CaretakerAddress { get; set; }
        public Nullable<long> AddressDistrict { get; set; }
        public string ContactNumber { get; set; }
        public string ClosestAliveRelative { get; set; }
        public string RelativeAddress { get; set; }
        public string RelativeContactNumber { get; set; }
        public System.DateTime DataCollectionDate { get; set; }
        public System.DateTime ChildCareInstitutionEnrollDate { get; set; }
        public string ChildConsentToFostering { get; set; }
        public string BiologicalParentsConsentToFostering { get; set; }
        public string InCCIFor { get; set; }
        public string PotentialForFoster { get; set; }
        public string IsFostering { get; set; }
        public Nullable<long> PlacementDistrict { get; set; }
        public Nullable<long> MonitoringDistrict { get; set; }
        public System.DateTime LastFollowUpDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual AdminLoginTbl AdminLoginTbl { get; set; }
        public virtual CCIMasterTbl CCIMasterTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl1 { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl2 { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildParentConnectionTbl> ChildParentConnectionTbls { get; set; }
    }
}
