//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildIndividualTbl
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Age { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> District { get; set; }
        public Nullable<long> Tehsil { get; set; }
        public string ChildName { get; set; }
        public Nullable<double> ChildAge { get; set; }
        public string ChildGender { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<long> ChildState { get; set; }
        public Nullable<long> ChildDistrict { get; set; }
        public Nullable<long> ChildTehsil { get; set; }
        public string SocialCategory { get; set; }
        public Nullable<long> ChildCategory { get; set; }
        public string ChildImage { get; set; }
        public string Otherillness { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifieddDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual ChildCategoryTbl ChildCategoryTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl1 { get; set; }
        public virtual StateMasterTbl StateMasterTbl { get; set; }
        public virtual StateMasterTbl StateMasterTbl1 { get; set; }
        public virtual TehsilMasterTbl TehsilMasterTbl { get; set; }
        public virtual TehsilMasterTbl TehsilMasterTbl1 { get; set; }
    }
}
