//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FosterCareDBEntities : DbContext
    {
        public FosterCareDBEntities()
            : base("name=FosterCareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLoginTbl> AdminLoginTbls { get; set; }
        public virtual DbSet<CCIMasterTbl> CCIMasterTbls { get; set; }
        public virtual DbSet<ChildCategoryTbl> ChildCategoryTbls { get; set; }
        public virtual DbSet<ChildIndividualTbl> ChildIndividualTbls { get; set; }
        public virtual DbSet<ChildInstitutionTbl> ChildInstitutionTbls { get; set; }
        public virtual DbSet<ChildMasterTbl> ChildMasterTbls { get; set; }
        public virtual DbSet<ChildParentConnectionTbl> ChildParentConnectionTbls { get; set; }
        public virtual DbSet<DistrictMasterTbl> DistrictMasterTbls { get; set; }
        public virtual DbSet<EnquiryTbl> EnquiryTbls { get; set; }
        public virtual DbSet<FosterParentTbl> FosterParentTbls { get; set; }
        public virtual DbSet<ModuleMasterTbl> ModuleMasterTbls { get; set; }
        public virtual DbSet<ParentMasterTbl> ParentMasterTbls { get; set; }
        public virtual DbSet<PermissionMasterTbl> PermissionMasterTbls { get; set; }
        public virtual DbSet<PotentialParentMaster> PotentialParentMasters { get; set; }
        public virtual DbSet<RoleMasterTbl> RoleMasterTbls { get; set; }
        public virtual DbSet<StateMasterTbl> StateMasterTbls { get; set; }
        public virtual DbSet<TehsilMasterTbl> TehsilMasterTbls { get; set; }
    }
}
