//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class FosterParentTbl
    {
        public long Id { get; set; }
        public string FosterCareFor { get; set; }
        public string FosterParentName { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> District { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Age { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string ReasonForFosterCare { get; set; }
        public string OtherReasone { get; set; }
        public string Education { get; set; }
        public string OtherEducation { get; set; }
        public string Occupation { get; set; }
        public string MaritalStatus { get; set; }
        public string NameOfSpouse { get; set; }
        public Nullable<double> AgeOfSpouse { get; set; }
        public string OccupationOfSpouse { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual DistrictMasterTbl DistrictMasterTbl { get; set; }
        public virtual StateMasterTbl StateMasterTbl { get; set; }
    }
}
