//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentMasterTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParentMasterTbl()
        {
            this.ChildParentConnectionTbls = new HashSet<ChildParentConnectionTbl>();
        }
    
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public long FosterParentSerialNumber { get; set; }
        public Nullable<long> FosterParentDistrict { get; set; }
        public string ParentCode { get; set; }
        public string FosterMothersName { get; set; }
        public System.DateTime FosterMothersDOB { get; set; }
        public string FosterMotherCurrentStatus { get; set; }
        public string FosterMotherHighestEducation { get; set; }
        public string FosterMotherEmploymentStatus { get; set; }
        public string FosterMotherIncome { get; set; }
        public string FosterFathersName { get; set; }
        public System.DateTime FosterFathersDOB { get; set; }
        public string FosterFathersCurrentStatus { get; set; }
        public string FosterFathersHighestEducation { get; set; }
        public string FosterFathersEmploymentStatus { get; set; }
        public string FosterFathersIncome { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<long> FosterGirlsCount { get; set; }
        public Nullable<long> FosterBoysCount { get; set; }
        public Nullable<long> RationCardFosterChildrenCount { get; set; }
        public string AnyOtherFosters { get; set; }
        public Nullable<long> ChildSheetFosteredChildrenCount { get; set; }
        public Nullable<long> AdoptedChildrenCount { get; set; }
        public Nullable<long> BiologicalChildrenCount { get; set; }
        public System.DateTime PlacementDate { get; set; }
        public string ReasonForFostering { get; set; }
        public System.DateTime LastExtensionDate { get; set; }
        public string ExtensionPeriod { get; set; }
        public System.DateTime TerminationDate { get; set; }
        public string ReasonForTermination { get; set; }
        public System.DateTime LastFollowUpDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual AdminLoginTbl AdminLoginTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildParentConnectionTbl> ChildParentConnectionTbls { get; set; }
        public virtual DistrictMasterTbl DistrictMasterTbl { get; set; }
    }
}
