//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotentialParentMaster
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public long SerialNumber { get; set; }
        public string ApplicantsName { get; set; }
        public string ApplicantsAddress { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime ApplicantsDOB { get; set; }
        public Nullable<double> Age { get; set; }
        public string ApplicantsHighestEducation { get; set; }
        public string MartialStatus { get; set; }
        public string DoYouHaveChildren { get; set; }
        public Nullable<long> ChildrenCount { get; set; }
        public string IsLegalCase { get; set; }
        public string IsKnowFosterCare { get; set; }
        public string YouWillingToFosterAChild { get; set; }
        public string AnyQuestion { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual AdminLoginTbl AdminLoginTbl { get; set; }
    }
}
