//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMasterTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleMasterTbl()
        {
            this.AdminLoginTbls = new HashSet<AdminLoginTbl>();
            this.PermissionMasterTbls = new HashSet<PermissionMasterTbl>();
        }
    
        public long Id { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> Isactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminLoginTbl> AdminLoginTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionMasterTbl> PermissionMasterTbls { get; set; }
    }
}
